In [46]:
import pandas as pd

In [47]:
df=pd.read_json("sample_airbnb.json")

In [48]:
df.head()

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '454250', 'host_url': 'https://www...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '4351675', 'date': '2013-04-29 04:00:...",NaN,NaN,NaN
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '52004703', 'host_url': 'https://w...","{'street': 'Fatih , İstanbul, Turkey', 'suburb...","{'availability_30': 30, 'availability_60': 60,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '149469150', 'date': '2017-05-04 04:0...",NaN,NaN,NaN
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",,"Clean, fully furnish, Spacious 1 bedroom flat ...",,,,,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51624384', 'host_url': 'https://w...","{'street': 'Hong Kong, Hong Kong Island, Hong ...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '56904633', 'date': '2015-12-19 05:00...",5000.0,NaN,NaN
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...","Living Room , Kitchen and Toilet, All cooking ...",...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51744313', 'host_url': 'https://w...","{'street': 'Hong Kong , 九龍, Hong Kong', 'subur...","{'availability_30': 14, 'availability_60': 24,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '57191745', 'date': '2015-12-22 05:00...",1350.0,5000.0,NaN
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '13764143', 'host_url': 'https://w...","{'street': 'Surry Hills, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '123549502', 'date': '2016-12-29 05:0...",NaN,NaN,NaN

In [49]:
df.shape

(5555, 42)

In [50]:
df.describe()

,_id,minimum_nights,maximum_nights,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,security_deposit,cleaning_fee,extra_people,guests_included,weekly_price,monthly_price,reviews_per_month
count,5.555000e+03,5555.000000,5.555000e+03,5555.000000,5550.000000,5542.000000,5555.000000,5545.000000,5555.000000,3471.000000,4024.000000,5555.000000,5555.000000,714.000000,656.000000,94.000000
mean,1.664386e+07,5.564356,1.382776e+06,3.505851,1.411712,2.071454,27.606481,1.291163,278.766157,509.430424,94.074801,22.791899,1.747435,1530.903361,5391.370427,1.712766
std,9.622558e+06,22.613861,5.256920e+07,2.297019,1.041942,1.619660,49.798376,0.702265,842.215531,1594.805320,110.203782,69.331511,1.487352,3185.916331,12723.569651,1.492795
min,1.170800e+04,1.000000,1.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,0.000000,0.000000,1.000000,60.000000,250.000000,1.000000
25%,8.376039e+06,1.000000,5.900000e+01,2.000000,1.000000,1.000000,1.000000,1.000000,70.000000,0.000000,23.000000,0.000000,1.000000,480.250000,1505.250000,1.000000
50%,1.711345e+07,2.000000,1.125000e+03,3.000000,1.000000,2.000000,5.000000,1.000000,129.000000,200.000000,60.000000,0.000000,1.000000,800.000000,2800.000000,1.000000
75%,2.461229e+07,3.000000,1.125000e+03,4.000000,2.000000,3.000000,32.000000,1.000000,280.000000,500.000000,129.000000,20.000000,2.000000,1575.250000,4800.000000,2.000000
max,3.295874e+07,1250.000000,2.147484e+09,16.000000,20.000000,25.000000,533.000000,16.000000,48842.000000,39228.000000,2000.000000,2346.000000,16.000000,59123.000000,253384.000000,10.000000

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5555 entries, 0 to 5554
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    5555 non-null   int64
 1   listing_url            5555 non-null   object
 2   name                   5555 non-null   object
 3   summary                5555 non-null   object
 4   space                  5555 non-null   object
 5   description            5555 non-null   object
 6   neighborhood_overview  5555 non-null   object
 7   notes                  5555 non-null   object
 8   transit                5555 non-null   object
 9   access                 5555 non-null   object
 10  interaction            5555 non-null   object
 11  house_rules            5555 non-null   object
 12  property_type          5555 non-null   object
 13  room_type              5555 non-null   object
 14  bed_type               5555 non-null   object
 15  minimum_nights         5555 non-null   int64
 16  maximum_nights         5555 non-null   int64
 17  cancellation_policy    5555 non-null   object
 18  last_scraped           5555 non-null   object
 19  calendar_last_scraped  5555 non-null   object
 20  first_review           4167 non-null   object
 21  last_review            4167 non-null   object
 22  accommodates           5555 non-null   int64
 23  bedrooms               5550 non-null   float64
 24  beds                   5542 non-null   float64
 25  number_of_reviews      5555 non-null   int64
 26  bathrooms              5545 non-null   float64
 27  amenities              5555 non-null   object
 28  price                  5555 non-null   int64
 29  security_deposit       3471 non-null   float64
 30  cleaning_fee           4024 non-null   float64
 31  extra_people           5555 non-null   int64
 32  guests_included        5555 non-null   int64
 33  images                 5555 non-null   object
 34  host                   5555 non-null   object
 35  address                5555 non-null   object
 36  availability           5555 non-null   object
 37  review_scores          5555 non-null   object
 38  reviews                5555 non-null   object
 39  weekly_price           714 non-null    float64
 40  monthly_price          656 non-null    float64
 41  reviews_per_month      94 non-null     float64
dtypes: float64(8), int64(8), object(26)
memory usage: 1.8+ MB

In [52]:
df['cleaning_fee'].head()

0    135.0
1      NaN
2      NaN
3     50.0
4     50.0
Name: cleaning_fee, dtype: float64

In [53]:
df['neighborhood_overview'].head()

0    Great neighborhood - many terrific restaurants...
1    Cankurtaran mahallesi akbıyık caddesi no 22 Su...
2
3    Cheapest food, electronic device, clothing and...
4    Surry Hills is a vibrant eclectic community an...
Name: neighborhood_overview, dtype: object

In [54]:
df['transit'].head()

0    Conveniently located near 1, 2, 3, B & C subwa...
1     Tram 5 minutes  metro 10 minutes  Bus 10 minutes
2
3    Close to 3 different MTR Station, Sham shui Po...
4    Travel Card 'Opal' travel cards work on all Sy...
Name: transit, dtype: object

In [55]:
propertytype_count=df['property_type'].value_counts()

In [56]:
propertytype_count

property_type
Apartment                 3626
House                      606
Condominium                399
Serviced apartment         185
Loft                       142
Townhouse                  108
Guest suite                 81
Bed and breakfast           69
Boutique hotel              53
Guesthouse                  50
Hostel                      34
Villa                       32
Hotel                       26
Aparthotel                  23
Cottage                     20
Other                       18
Cabin                       15
Bungalow                    14
Resort                      11
Farm stay                    9
Casa particular (Cuba)       9
Tiny house                   7
Boat                         2
Nature lodge                 2
Chalet                       2
Camper/RV                    2
Pension (South Korea)        1
Houseboat                    1
Castle                       1
Campsite                     1
Treehouse                    1
Heritage hotel (India)       1
Hut                          1
Barn                         1
Earth house                  1
Train                        1
Name: count, dtype: int64

In [57]:
df['price'].value_counts()

price
60      137
100     127
50      126
70      102
90       93
       ...
2611      1
690       1
5502      1
1321      1
387       1
Name: count, Length: 649, dtype: int64

In [58]:
df.dtypes

_id                        int64
listing_url               object
name                      object
summary                   object
space                     object
description               object
neighborhood_overview     object
notes                     object
transit                   object
access                    object
interaction               object
house_rules               object
property_type             object
room_type                 object
bed_type                  object
minimum_nights             int64
maximum_nights             int64
cancellation_policy       object
last_scraped              object
calendar_last_scraped     object
first_review              object
last_review               object
accommodates               int64
bedrooms                 float64
beds                     float64
number_of_reviews          int64
bathrooms                float64
amenities                 object
price                      int64
security_deposit         float64
cleaning_fee             float64
extra_people               int64
guests_included            int64
images                    object
host                      object
address                   object
availability              object
review_scores             object
reviews                   object
weekly_price             float64
monthly_price            float64
reviews_per_month        float64
dtype: object

In [59]:
df['address'][1]

{'street': 'Fatih , İstanbul, Turkey',
 'suburb': 'Fatih',
 'government_area': 'Fatih',
 'market': 'Istanbul',
 'country': 'Turkey',
 'country_code': 'TR',
 'location': {'type': 'Point',
  'coordinates': [28.98009, 41.0062],
  'is_location_exact': False}}

In [60]:
df['availability'][0]

{'availability_30': 0,
 'availability_60': 0,
 'availability_90': 0,
 'availability_365': 93}

In [61]:
df['reviews'][0]

[{'_id': '4351675',
  'date': '2013-04-29 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '3708459',
  'reviewer_name': 'Josh',
  'comments': "i had a really pleasant stay at greta's place. the location is super convenient -- and the area is fun, with lots of hidden gems. the apartment was comfortable and charming. greta was accommodating and hospitable and left some great cupcakes in the fridge. i give this place a strong endorsement."},
 {'_id': '4848277',
  'date': '2013-05-28 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '4609491',
  'reviewer_name': 'Ralf',
  'comments': 'Greta has been a great host, and her apartment a great place to stay. Perfectly located for our adventures around NYC, it is a place full of character and, as I see it, a very authentic NY Apartment that makes you feel at home imediately. Great neighbourhood, great infrastructure around the apartment block. Very good for a perfect stay.'},
 {'_id': '5094175',
  'date': '2013-06-11 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '6741662',
  'reviewer_name': 'Mame',
  'comments': "Greta was wonderful. We arrived late at night and she made sure we were able to get in. We also had to transfer to a hotel for work, and she allowed us to keep our belongings there until 3 so we wouldn't be carting our luggage until we needed to. The apartment was clean and large and in a wonderful neighborhood. She had lists and menus of places to eat. I couldn't have been happier with our arrangement. Thanks Greta!"},
 {'_id': '5497796',
  'date': '2013-07-02 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '474156',
  'reviewer_name': 'Lars',
  'comments': "Greta's place is very well located, so close to the MTA 1 line, which takes you up and down Manhattan, which was perfect for me.  It was an easy 3 minute walk and be on your way to anywhere in NY. \r\nThe shower is something else, the best water pressure I have experienced in a long time.\r\nI thought the decor was cool and eclectic, Greta must have an artistic streak. The Murphy bed was comfortable, and the AC unit (not pictured) kept it nice and cool.  \r\nAlthough I didn't meet her, she arranged for a neighbor to meet me and show me in. He was cool and so were any other neighbors that I met. \r\nShe also left a list of suggestions where to shop and eat, along with menus which was helpful when I needed a late night meal. \r\nHighly recommended. \r\n"},
 {'_id': '6933005',
  'date': '2013-08-31 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '6067127',
  'reviewer_name': 'Nicole',
  'comments': "I had a wonderful stay at Greta's NYC apartment. The apartment was clean and comfortable. She was a wonderful and informative host. I felt very welcomed in her home."},
 {'_id': '7205029',
  'date': '2013-09-10 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '7743438',
  'reviewer_name': 'Ute',
  'comments': 'Hi Greta,\r\nyou have a wonderful place. We had a great time an felt really comfortable - little bit like beeing home in NY :)\r\nEverything worked out pretty good, also the connection to La Guardia Airport was perfect.\r\n\r\nThanks again :)\r\n'},
 {'_id': '7464858',
  'date': '2013-09-21 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '8543724',
  'reviewer_name': 'Drew',
  'comments': 'Greta was very welcoming and helpful. Prompt email communication.\r\n\r\nA great stay for those in town to see Broadway shows, shopping or sight seeing the West Side. A few minutes walking and I was in Central Park.\r\n\r\nA definite recommendation.'},
 {'_id': '7515354',
  'date': '2013-09-23 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '1683177',
  'reviewer_name': 'Don',
  'comments': 'Greta was flexible about our sign-in time, helpful as we arrived, and kind to return to us a bag that we left in her apartment.  The apartment is wonderfully located for transportation and things to do.  It is compact and comfy, full of interesting books and prints.  The bed is quite firm.'},
 {'_id': '7871931',
  'date': '2013-10-07 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '2871729',
  'reviewer_name': 'Heidi',
  'comments': 'We spent three nights in Greta’s apartment. Her kitchen is fully-equipped and the sleeping arrangements are extremely comfortable. Greta is a very accommodating host and easy to communicate with. She was very gracious about our later-than-expected arrival and allowed us to stay in her apartment on our departure day until we left for an early evening flight. Her apartment is very well-located, with food markets, drug stores, restaurants and coffee shops within a block of her building. The building is ½ block from the #1 subway line, enabling easy access to all parts of Manhattan.'},
 {'_id': '8136769',
  'date': '2013-10-17 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '7811780',
  'reviewer_name': 'Julia',
  'comments': "We enjoyed our stay in Greta's apartment very much. The location is perfect, near Central Park, Broadway and everything, and the apartment is extremely cosy. Greta was very welcoming and helpful. We had a great time and felt really comfortable. Thanks :-)\r\n"},
 {'_id': '8210485',
  'date': '2013-10-21 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '8119019',
  'reviewer_name': 'Diane',
  'comments': "Our stay are Greta's was wonderful- she was so accomodating and welcoming.  Her apartment is lovely and such a great place to unwind from the hurried family weekend weekend we had.  Greta even accomodated the joining of my niece and nephew for one of the two nights with no problem.. Thank you so much, Greta, for your hospitality!  "},
 {'_id': '8478870',
  'date': '2013-11-02 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '8140760',
  'reviewer_name': 'Linda',
  'comments': 'Greta was a gracious and accommodating host, even coming over during our stay to reset the wifi connections.  The location of the apartment is ideal, basically half a short block to the subway.  Her list of neighborhood restaurants was very helpful and we sampled as many as we were able to. She has everything organized well.'},
 {'_id': '8587648',
  'date': '2013-11-06 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '9307997',
  'reviewer_name': 'Maureen',
  'comments': "Greta's apartment was comfortable and clean and the neighborhood was easily accessible to museums and other locations. A bit noisy at night."},
 {'_id': '8768655',
  'date': '2013-11-17 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '9464736',
  'reviewer_name': 'George',
  'comments': 'Greta was extremely helpful throughout this process!  Communication was maintained throughout the process and throughout our stay.  She was able to answer any questions we had and even gave suggestions for us.  Her instructions were awesome and the information left at her apartment were great!  There was even a binder with additional information like places to eat and places to go.  She even took the time to make sure we knew how to use the radiator!  Being from Hawaii, we had no knowledge about radiators and how to use them - we really appreciated her thoughtfulness!'},
 {'_id': '9179262',
  'date': '2013-12-11 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '9405167',
  'reviewer_name': 'Whitney',
  'comments': "Greta's apartment was homey, clean and just the right size for two (probably even three) people. Greta was extremely helpful in getting us settled and providing information about the neighborhood....etc. Murphy bed was very firm but comfortable. Great water pressure in shower. Apt is close to everything and  the neighborhood has so much to offer. I would definitely recommend Greta's place.  "},
 {'_id': '9428838',
  'date': '2013-12-28 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '10297643',
  'reviewer_name': 'Deborah & Tim',
  'comments': "The apartment is very homey - it felt like I was staying in a friend's apartment. The bed is surprisingly comfy and firm (I have never slept in a Murphy bed before) and the shower had plenty of hot water and great pressure. Greta was very communicative and friendly, and was also incredibly accommodating when I had something come up unexpectedly and needed to stay a couple hours longer than I anticipated. Overall all it was a very cozy stay in a great location!"},
 {'_id': '9543118',
  'date': '2014-01-02 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '8828184',
  'reviewer_name': 'Catherine',
  'comments': 'The location of this appartment was ideal! Just minutes away the subway and walking distance from Central Park, Riverside Park, and many good restaurants on Broadway. A quaint appartment, with a lot of cachet. I recommend it!!'},
 {'_id': '20872115',
  'date': '2014-10-06 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '7838233',
  'reviewer_name': 'Brandon',
  'comments': 'What a delightful apartment!  I plan to stay here next time I bring family to New York. I would describe the apartment as a very warm, personal, comfortable and homey place to stay. It’s a corner apartment with good light, lots of books and  very good energy. Plus, the beds are quite comfortable. My daughter exclaimed “Hey Dad, come lie down in this one. You’ll never want to get up!”\r\n\r\nThe neighborhood was incredibly well located and enjoyable. The train stops  a half block away, and there are numerous excellent restaurants and conveniences close by. Greta, the host, provides a first-rate list of recommendations.\r\n\r\nGreta was a personable, helpful and extremely welcoming host. She was very quick to respond to my online inquiries and, once we arrived, to any further requests for advice.\r\n'},
 {'_id': '22257920',
  'date': '2014-11-02 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '4034556',
  'reviewer_name': 'Aparna',
  'comments': 'Greta was a lovely host! She was communicative, helpful and flexible during the booking process and very responsive and friendly when we were at her place in NYC. The house is charming and comfortable, and very conveniently located right by the 1 train. We were two of us and only used one room, but the house can fit another person or two. \r\nFor anyone visiting NYC and looking to be in the city but not in the midst of the city noise, this is a great place to stay! You can be downtown in 20 minutes. '},
 {'_id': '23415037',
  'date': '2014-11-30 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '22685675',
  'reviewer_name': 'Karolina',
  'comments': "I stayed at Greta's place for 3 days! It was a really pleasant stay! The bed was really comfortable. The place was clean and cozy. A minute from the subway station! I didnt meet Greta in person, but we were communicating all the time and she was really helpful and kind with everything I needed! I would love to stay again the next time! :) i surely recommend it! "},
 {'_id': '23924172',
  'date': '2014-12-14 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '16534063',
  'reviewer_name': 'Paul',
  'comments': "Staying at Greta's apartment was delightful!  It's a wonderful, quirky New York apartment -- very compact, but also very comfy and accurately portrayed in the pictures.  The Murphy (fold-down) bed has a very thick memory foam mattress that is extremely comfortable.  Samantha (the cat) was a sweet little presence, but she kept mostly to herself so we barely saw her.  The location is great, less than a block to the 1 line, and there are several nice restaurants in the neighborhood.  Finally, Greta herself was a perfect host:  kind but not intrusive, thoughtful in her preparations for guests, and available should any problems arise (though none did).  A great airbnb experience!"},
 {'_id': '28737168',
  'date': '2015-03-29 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '29115141',
  'reviewer_name': 'Catherine',
  'comments': 'Greta was a great host.  She met us late on Friday and explained everything about the apartment which we found very comfortable and fun.  I would highly recommend this apartment to anyone.  It is not luxurious but well-equipped and I loved the location, near Central Park and easy walk to museums.\r\n'},
 {'_id': '29274122',
  'date': '2015-04-06 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '18417452',
  'reviewer_name': 'Paul',
  'comments': "Apt is beautifully as advertised, a comfortable place and beds, kitchen and bath. Arrival and departure were really well coordinated by host, the lovely Greta. Location is fabulously convenient on upper West side by subway, Amsterdam and Broadway restaurants, bars and history. We'd stay here again.  "},
 {'_id': '29610000',
  'date': '2015-04-10 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '27919376',
  'reviewer_name': 'Anika',
  'comments': 'Greta was a lovely host, making sure we settled in well and could contact her easily if there were any problems. \r\nThe apartment is cosy with very comfortable beds and a well equipped kitchen in case you need a place to cook. It is also a nice neighborhood, with a lot of great places to eat nearby and it is a minute away from a subway station, so you are well connected to the rest of the city. We had a great time! '},
 {'_id': '29775810',
  'date': '2015-04-12 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '20415509',
  'reviewer_name': 'Jane',
  'comments': 'My daughter and I stayed the weekend at Gretas place.  Greta was herself away for the weekend but everything was in great shape for us to stay and Greta was very available by phone for any questions.  Everything was very tidy and clean..comfy beds and good shower.  It was like home.  The location in the city is perfect..close to the park and subway.  I highly recommend Gretas home for aNew York stay!'},
 {'_id': '30732097',
  'date': '2015-04-26 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '10570759',
  'reviewer_name': 'Lakshmi',
  'comments': "Greta is an amazing host and her apartment was super convenient for my stay in Manhattan. Here are my reasons:\r\nFirst - she as a person made me feel super welcome. I requested her a really early check in and she agreed (which was helpful because I took a red eye from Seattle). She also allowed me to keep my bags after my check out time so I could pick it up before my flight.\r\nSecond - her apartment location is SUPER convenient. Right next to the #1 and pretty close to B and C lines. NYC is all about location is this fits perfectly.\r\nThird - her apartment gives the feel of a typical NYC apartment. It is tiny but has everything you need. Two beds, a great shower, clean towels, and a kitchen (which I didn't use). Safe building with elevator. \r\n\r\nI would totally stay here again.  "},
 {'_id': '31196460',
  'date': '2015-05-03 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '43102',
  'reviewer_name': 'Catherine Et Albert',
  'comments': "Greta was a fantastic host, we had a problem with a lost luggage at JFK and she helped us to coordinate the delivery. We also arrived later than scheduled in Manhattan, Greta was waiting for us, she welcomed us very friendly. The apartment is very nice and bright, the bed is very comfortable. Nice building with elevator, perfect location, between Riverside Park and Central Park, a block from the subway, lot of nice restaurants all around, we had a fantastic stay! Greta est une hôte fantastique, nous avons eu un problème de baggage à JFK et Greta nous a aidé à coordonner la livraison. Nous sommes arrivés plus tard que prévu et Greta nous a accueilli très chaleureseument. L'appartement est parfaitement situé, a un block du métro et entre Cantral Park et Riverside Park, il y a un ascenceur. Nombreux restaurants tout autour! Parfait nous recommandons vivement."},
 {'_id': '31845940',
  'date': '2015-05-10 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '14717479',
  'reviewer_name': 'Samantha',
  'comments': 'We had a great stay with Greta.  She was a good communicator, flexible, and her apartment is a good value for the neighborhood.  We will definitely think about staying with her again.'},
 {'_id': '33677946',
  'date': '2015-05-31 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '31114625',
  'reviewer_name': 'Rebecca',
  'comments': "My stay at Greta's place was perfect! The space is exactly as described, and was very clean and welcoming. Greta was very responsive to me, and even helped me figure out how to pick up the keys with my late arrival. Thank you!"},
 {'_id': '36960183',
  'date': '2015-07-03 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '33119724',
  'reviewer_name': 'Thomas',
  'comments': 'Greta was an excellent hostess and was very accommodating. She took care of the little things that made a difference such as providing an extra set of keys and having the air conditioning on prior to my arrival. The apartment was clean and very comfortable. It instantly felt like "home". The location of the apartment was great! There are multiple grocery stores, restaurants, bars, etc. within a very short walking distance. The subway stop was very conveniently located as was Central Park and Riverside Park, which are both beautiful places for an afternoon walk. I would and have recommended this listing to friends that are traveling to the city and I would stay there again without hesitation. '},
 {'_id': '37555310',
  'date': '2015-07-08 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '6352182',
  'reviewer_name': 'Murray',
  'comments': 'Greta is an excellent Airbnb host! She is warm, accommodating and very well organized. Her apt is located close to all amenities, Central and Riverside Parks, and bus/subway stops. The apt is clean, more spacious than expected, well stocked with anything you could possibly need, and has very comfortable beds and a first rate shower. I was travelling with my soon-to-be 17 year old daughter so she was thrilled to have her own bedroom! This is not fancy accommodation but warm and homey and probably a good representation of how an average New Yorker lives, although I suspect not many are as organized as Greta. Much recommended!'},
 {'_id': '48783685',
  'date': '2015-09-28 04:00:00',
  'listing_id': '1003530',
  'reviewer_id': '43967256',
  'reviewer_name': 'Judy',
  'comments': "I have used airbnb in NYC several times, and this, by far, was my best experience.  The location is on a quiet street and on the same block as a major subway line.  You can't get any better than that.  The apartment has all the conveniences of a home - everything you'd need in a kitchen, extremely comfortable mattress, cable TV, air conditioning, wifi, great water pressure.  \r\n\r\nGreata goes way out of her way to make your stay as enjoyable as possible.  Her recommendations are outstanding and the check-in and check-out were  extremely easy.  This is a five star host and you won't go wrong with this choice for a stay in NYC. \r\n"},
 {'_id': '53270568',
  'date': '2015-11-07 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '21960218',
  'reviewer_name': 'Nicky',
  'comments': "This is my second time staying at Greta's apartment. The best place to stay in NYC by far. There is a subway on the same street as the apartment, a two minute walk away (the 1 line) and multiple places to eat close by. There is also a CVS , Walgreens, grocery and liquor store within walking distance as well. The apartment is very clean and the bed is very comfortable. Checking in and out as easy as Greta is very flexible. The apartment is very spacious with a nice kitchen and lots of room in the fridge. I hope to continue to stay here every time I visit New York! "},
 {'_id': '57574836',
  'date': '2015-12-27 05:00:00',
  'listing_id': '1003530',
  'reviewer_id': '50466815',
  'reviewer_name': 'Obaseki',

In [62]:
df['space'][4]

"Comfortable studio with a great layout. The bathroom has a full size bath tub and shower. Complete set of kitchen utensils etc for cooking and a full size fridge. The 3 seater sofa and 42' TV mean you can comfortably relax after a day at the beach or exploring.  Large lounge room windows provide harbour views."

In [63]:
df['calendar_last_scraped'][0]

'2019-03-07 05:00:00'

In [64]:
df['bed_type'].value_counts()

bed_type
Real Bed         5506
Pull-out Sofa      26
Futon              10
Couch               7
Airbed              6
Name: count, dtype: int64

In [65]:
def extract_values_address(dictionary):
    street_name = dictionary['street']
    country_name = dictionary['country']
    country_code = dictionary['country_code']
    location_type = dictionary['location']['type']
    longitude = dictionary['location']['coordinates'][0]
    latitude = dictionary['location']['coordinates'][1]
    is_location_exact = dictionary['location']['is_location_exact']
    
    return street_name, country_name,country_code,location_type,longitude,latitude,is_location_exact

df[['street_name', 'country_name','country_code','location_type','longitude','latitude','is_location_exact']] = df['address'].apply(lambda x: pd.Series(extract_values_address(x)))

In [66]:
df['country_name'].value_counts()

country_name
United States    1222
Turkey            661
Canada            649
Spain             633
Australia         610
Brazil            606
Hong Kong         600
Portugal          555
China              19
Name: count, dtype: int64

In [67]:
df['review_scores'][0]

{'review_scores_accuracy': 10,
 'review_scores_cleanliness': 9,
 'review_scores_checkin': 10,
 'review_scores_communication': 10,
 'review_scores_location': 10,
 'review_scores_value': 10,
 'review_scores_rating': 94}

In [68]:
def extract_values_review_score(dictionary):
    review_scores_rating = dictionary.get('review_scores_rating',None)
    return review_scores_rating

df[['review_scores_rating']] = df['review_scores'].apply(lambda x: pd.Series(extract_values_review_score(x)))

In [69]:
df['review_scores_rating'].value_counts()

review_scores_rating
100.0    982
98.0     291
96.0     286
97.0     281
95.0     259
93.0     244
94.0     223
90.0     213
99.0     188
80.0     167
92.0     158
89.0     113
91.0     112
87.0      97
88.0      77
85.0      55
86.0      48
84.0      43
60.0      41
83.0      39
70.0      25
82.0      19
20.0      16
81.0      12
75.0      11
78.0      11
40.0      10
76.0       9
73.0       8
79.0       8
74.0       5
72.0       5
67.0       5
71.0       4
77.0       4
65.0       3
68.0       3
69.0       2
50.0       2
53.0       1
64.0       1
Name: count, dtype: int64

In [70]:
df['availability'][0]

{'availability_30': 0,
 'availability_60': 0,
 'availability_90': 0,
 'availability_365': 93}

In [71]:
def extract_values_availability(dictionary):
    availability_365 = dictionary['availability_365']
    return availability_365

df[['availability_365']] = df['availability'].apply(lambda x: pd.Series(extract_values_availability(x)))

In [72]:
df['availability_365'].value_counts()

availability_365
0      1193
365     412
364     122
90       68
179      67
       ...
214       2
110       2
213       2
121       1
195       1
Name: count, Length: 366, dtype: int64

In [73]:
df[['room_type','property_type','accommodates','bedrooms','beds','bathrooms','availability_365']].tail(20)

,room_type,property_type,accommodates,bedrooms,beds,bathrooms,availability_365
5535,Entire home/apt,Apartment,2,1.0,1.0,1.0,0
5536,Entire home/apt,House,6,3.0,3.0,1.5,0
5537,Entire home/apt,Apartment,8,2.0,2.0,3.0,0
5538,Private room,Bed and breakfast,2,1.0,1.0,1.0,365
5539,Entire home/apt,Loft,4,0.0,2.0,1.0,305
5540,Entire home/apt,Apartment,3,1.0,1.0,1.0,0
5541,Entire home/apt,Apartment,4,1.0,2.0,1.0,300
5542,Private room,Apartment,2,1.0,2.0,0.5,365
5543,Entire home/apt,Loft,2,0.0,1.0,1.0,89
5544,Entire home/apt,Condominium,6,2.0,3.0,2.0,243
5545,Private room,Aparthotel,3,1.0,3.0,1.0,53
5546,Entire home/apt,Apartment,16,8.0,8.0,4.0,351
5547,Entire home/apt,Apartment,2,1.0,1.0,1.0,154
5548,Private room,Apartment,1,1.0,1.0,1.0,365
5549,Entire home/apt,Apartment,4,1.0,2.0,1.0,275
5550,Entire home/apt,House,2,2.0,3.0,1.0,365
5551,Entire home/apt,Townhouse,6,2.0,4.0,2.0,258
5552,Private room,Apartment,1,1.0,1.0,1.0,353
5553,Private room,Apartment,2,1.0,1.0,1.0,0
5554,Entire home/apt,Apartment,6,1.0,2.0,2.0,0

In [74]:
df['host'][6]

{'host_id': '34607505',
 'host_url': 'https://www.airbnb.com/users/show/34607505',
 'host_name': 'Scott',
 'host_location': 'New York, New York, United States',
 'host_about': 'I am pretty much your average early/mid career working professional in NYC.',
 'host_thumbnail_url': 'https://a0.muscache.com/im/pictures/675cec89-71eb-4ca7-bacd-bbed62ef6fad.jpg?aki_policy=profile_small',
 'host_picture_url': 'https://a0.muscache.com/im/pictures/675cec89-71eb-4ca7-bacd-bbed62ef6fad.jpg?aki_policy=profile_x_medium',
 'host_neighbourhood': 'Chelsea',
 'host_is_superhost': False,
 'host_has_profile_pic': True,
 'host_identity_verified': True,
 'host_listings_count': 1,
 'host_total_listings_count': 1,
 'host_verifications': ['email', 'phone', 'facebook', 'reviews', 'kba']}

In [75]:
def extract_values_host(dictionary):
    host_id = dictionary['host_id']
    host_name = dictionary['host_name'] 
    host_location=dictionary['host_location']
    host_neighbourhood = dictionary.get('host_neighbourhood', None)
    host_verifications=dictionary.get('host_verifications',[])
    government_id = None
    for verification in host_verifications:
        if verification == 'government_id':
            government_id = verification
            break
    return host_id,host_name, host_neighbourhood,host_location,government_id

df[['host_id','host_name','host_neighbourhood','host_location','government_id']] = df['host'].apply(lambda x: pd.Series(extract_values_host(x)))

In [76]:
df[['host_id','host_name','host_neighbourhood','host_location','country_name','government_id']].head(20)

,host_id,host_name,host_neighbourhood,host_location,country_name,government_id
0,454250,Greta,,"New York, New York, United States",United States,government_id
1,52004703,Mehmet Emin,,"Istanbul, İstanbul, Turkey",Turkey,government_id
2,51624384,Giovanni,Soho,"Hong Kong, Hong Kong",Hong Kong,government_id
3,51744313,Yi,Shek Kip Mei,United States,Hong Kong,government_id
4,13764143,Ben,Surry Hills,"New South Wales, Australia",Australia,government_id
5,2649859,Elisabete,,"Porto, Porto, Portugal",Portugal,government_id
6,34607505,Scott,Chelsea,"New York, New York, United States",United States,None
7,1017772,Lane,Jamaica,US,United States,government_id
8,11275734,Josh,Bushwick,"New York, New York, United States",United States,None
9,51530266,Ana Valéria,Copacabana,"Rio de Janeiro, State of Rio de Janeiro, Brazil",Brazil,government_id
10,7140229,Caro,,"Montreal, Quebec, Canada",Canada,government_id
11,51915770,Luiz Rodrigo,,"Rio de Janeiro, State of Rio de Janeiro, Brazil",Brazil,None
12,1282196,Ynaie,Jardim Botânico,"Rio de Janeiro, State of Rio de Janeiro, Brazil",Brazil,None
13,9036477,Margaux,Le Plateau,"Montreal, Quebec, Canada",Canada,None
14,51471538,Ahmet,Şişli,"Istanbul, İstanbul, Turkey",Turkey,None
15,27518920,Fábio,,"São Félix da Marinha, Porto, Portugal",Portugal,government_id
16,51920973,Manuela,,"Porto, Porto District, Portugal",Portugal,government_id
17,52004369,Chelsea,,"Sea Cliff, New York, United States",United States,government_id
18,51326285,Beatriz,Catete,"Rio de Janeiro, State of Rio de Janeiro, Brazil",Brazil,government_id
19,51289938,Ken,Jordan,Hong Kong,Hong Kong,None

In [77]:
df['host_id'].value_counts()

host_id
97240131     18
12243051     11
4459553       9
38459934      9
3953109       7
             ..
134946389     1
2737232       1
10262420      1
50729124      1
47092481      1
Name: count, Length: 5104, dtype: int64

In [78]:
df['minimum_nights'].value_counts()

minimum_nights
1       1862
2       1505
3        882
4        296
5        269
7        178
30       116
32        80
6         62
31        46
10        38
28        36
14        31
29        25
15        22
60        15
21        12
180       12
90        12
20         9
8          5
12         5
120        4
25         4
27         3
9          3
365        2
13         2
45         2
16         2
115        1
1250       1
80         1
200        1
300        1
22         1
100        1
179        1
40         1
11         1
35         1
26         1
96         1
160        1
50         1
Name: count, dtype: int64

In [79]:
df['maximum_nights'].value_counts()

maximum_nights
1125    3160
30       361
365      192
90       168
60       132
        ...
720        1
140        1
103        1
69         1
224        1
Name: count, Length: 140, dtype: int64

In [80]:
df['government_id'].value_counts()

government_id
government_id    3146
Name: count, dtype: int64

In [81]:
df['government_id'].item

<bound method IndexOpsMixin.item of 0       government_id
1       government_id
2       government_id
3       government_id
4       government_id
            ...
5550             None
5551             None
5552             None
5553             None
5554             None
Name: government_id, Length: 5555, dtype: object>

In [82]:
df['is_location_exact'].value_counts()

is_location_exact
True     3735
False    1820
Name: count, dtype: int64

In [83]:
df['reviews_per_month'].isnull().mean()*100

98.30783078307832

In [84]:
df[['host_id','host_name','host_location']].value_counts().head(10)

host_id    host_name             host_location
97240131   Jov                   Hong Kong, Hong Kong                        18
12243051   Sonder                San Francisco, California, United States    11
38459934   Alejandro             Montreal, Québec, Canada                     9
4459553    Eva&Jacques           Barcelona, Catalonia, Spain                  9
30907275   Liiiving              Porto, Porto District, Portugal              7
3953109    Feels Like Home       Lisbon, Lisboa, Portugal                     7
122131447  Debe                  中国广东省梅州市梅江区东山大道武警路口金福花园                      6
74079684   Marina                Honolulu, Hawaii, United States              6
43793840   Mark                  Honolulu, Hawaii, United States              6
69552498   Captain Cook Resorts  Honolulu, Hawaii, United States              6
Name: count, dtype: int64

In [85]:
df.dtypes

_id                        int64
listing_url               object
name                      object
summary                   object
space                     object
description               object
neighborhood_overview     object
notes                     object
transit                   object
access                    object
interaction               object
house_rules               object
property_type             object
room_type                 object
bed_type                  object
minimum_nights             int64
maximum_nights             int64
cancellation_policy       object
last_scraped              object
calendar_last_scraped     object
first_review              object
last_review               object
accommodates               int64
bedrooms                 float64
beds                     float64
number_of_reviews          int64
bathrooms                float64
amenities                 object
price                      int64
security_deposit         float64
cleaning_fee             float64
extra_people               int64
guests_included            int64
images                    object
host                      object
address                   object
availability              object
review_scores             object
reviews                   object
weekly_price             float64
monthly_price            float64
reviews_per_month        float64
street_name               object
country_name              object
country_code              object
location_type             object
longitude                float64
latitude                 float64
is_location_exact           bool
review_scores_rating     float64
availability_365           int64
host_id                   object
host_name                 object
host_neighbourhood        object
host_location             object
government_id             object
dtype: object

In [86]:
#compare government id
#compare highest hosted host in airbnb
#compare price
#world map longitude and latitude
#is_exact_location
#room type, property type
#available 365
#review score rating
#property type value count
#review score rating may be with property type or room type
#bedrooms , beds
#cancellation policy
#accommodates
#monthly price VS weeekly price

In [87]:
df['bedrooms'].value_counts()

bedrooms
1.0     3308
2.0     1090
0.0      496
3.0      427
4.0      161
5.0       36
6.0       16
7.0        7
8.0        3
9.0        2
10.0       2
20.0       1
15.0       1
Name: count, dtype: int64

In [88]:
df['beds'].value_counts()

beds
1.0     2700
2.0     1381
3.0      657
4.0      385
5.0      166
6.0      109
7.0       43
0.0       29
8.0       28
10.0      16
9.0       11
12.0       5
11.0       3
15.0       2
14.0       2
16.0       2
25.0       1
13.0       1
18.0       1
Name: count, dtype: int64

In [89]:
df.columns

Index(['_id', 'listing_url', 'name', 'summary', 'space', 'description',
       'neighborhood_overview', 'notes', 'transit', 'access', 'interaction',
       'house_rules', 'property_type', 'room_type', 'bed_type',
       'minimum_nights', 'maximum_nights', 'cancellation_policy',
       'last_scraped', 'calendar_last_scraped', 'first_review', 'last_review',
       'accommodates', 'bedrooms', 'beds', 'number_of_reviews', 'bathrooms',
       'amenities', 'price', 'security_deposit', 'cleaning_fee',
       'extra_people', 'guests_included', 'images', 'host', 'address',
       'availability', 'review_scores', 'reviews', 'weekly_price',
       'monthly_price', 'reviews_per_month', 'street_name', 'country_name',
       'country_code', 'location_type', 'longitude', 'latitude',
       'is_location_exact', 'review_scores_rating', 'availability_365',
       'host_id', 'host_name', 'host_neighbourhood', 'host_location',
       'government_id'],
      dtype='object')

In [90]:
df['cancellation_policy'].value_counts()

cancellation_policy
strict_14_with_grace_period    2420
flexible                       1682
moderate                       1336
super_strict_60                  79
super_strict_30                  38
Name: count, dtype: int64

In [91]:
df['accommodates'].value_counts()

accommodates
2     2052
4     1154
3      567
1      561
6      505
5      264
8      191
7       83
10      67
12      31
9       30
16      23
14      11
11       7
13       6
15       3
Name: count, dtype: int64

In [92]:
df['weekly_price'].value_counts()

weekly_price
600.0     25
500.0     23
400.0     18
700.0     17
1000.0    16
          ..
8899.0     1
6702.0     1
8934.0     1
1004.0     1
730.0      1
Name: count, Length: 323, dtype: int64

In [48]:
df['monthly_price'].value_counts()

monthly_price
3000.0     19
1500.0     17
2000.0     16
1000.0     15
4000.0     13
           ..
15818.0     1
1599.0      1
19500.0     1
9530.0      1
840.0       1
Name: count, Length: 309, dtype: int64

In [49]:
df['notes'][105]

"Just feel as home. We will give you all assistance. The 3rd guest is allowed to sleep on the sofa in the living room, and it's subject to an extra charge HK$250 per night."

In [50]:
df['interaction'][1056]

'Upon check-in I will give all the information necessary for a great stay in Porto and useful contacts.'

In [51]:
df['host_neighbourhood'].value_counts()

host_neighbourhood
                             1923
Copacabana                    124
Le Plateau                    123
Mong Kok                       90
Waikiki                        76
                             ...
Battery Park City               1
Pointe-Claire                   1
Opéra - Grands Boulevards       1
Breakfast Point/Cabarita        1
Rio Comprido                    1
Name: count, Length: 447, dtype: int64

In [52]:
df['host_neighbourhood'][5]

''

In [53]:
df.fillna(0)

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,...,longitude,latitude,is_location_exact,review_scores_rating,availability_365,host_id,host_name,host_neighbourhood,host_location,government_id
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,...,-73.965230,40.799620,False,94.0,93,454250,Greta,,"New York, New York, United States",government_id
1,10133554,https://www.airbnb.com/rooms/10133554,Double and triple rooms Blue mosque,,We are on the central city Blue mosque 5 minu...,We are on the central city Blue mosque 5 minu...,Cankurtaran mahallesi akbıyık caddesi no 22 Su...,,Tram 5 minutes metro 10 minutes Bus 10 minutes,"We have bathroom,wc,İnternet in rooms and unde...",...,28.980090,41.006200,False,92.0,365,52004703,Mehmet Emin,,"Istanbul, İstanbul, Turkey",government_id
2,10059872,https://www.airbnb.com/rooms/10059872,"Soho Cozy, Spacious and Convenient","Clean, fully furnish, Spacious 1 bedroom flat ...",,"Clean, fully furnish, Spacious 1 bedroom flat ...",,,,,...,114.150270,22.281580,True,100.0,0,51624384,Giovanni,Soho,"Hong Kong, Hong Kong",government_id
3,10084023,https://www.airbnb.com/rooms/10084023,City center private room with bed,House is located 5mins walk from Sham Shui Po ...,"The house is old fashion type, and paint the w...",House is located 5mins walk from Sham Shui Po ...,"Cheapest food, electronic device, clothing and...",Deposit of $1000 will be charged and will retu...,"Close to 3 different MTR Station, Sham shui Po...","Living Room , Kitchen and Toilet, All cooking ...",...,114.166900,22.331400,True,92.0,220,51744313,Yi,Shek Kip Mei,United States,government_id
4,10091713,https://www.airbnb.com/rooms/10091713,Surry Hills Studio - Your Perfect Base in Sydney,"This spacious, light filled studio has everyth...",Comfortable studio with a great layout. The ba...,"This spacious, light filled studio has everyth...",Surry Hills is a vibrant eclectic community an...,"WiFi, Apple TV with Netflix App (for use with ...",Travel Card 'Opal' travel cards work on all Sy...,You have full use of the entire studio and com...,...,151.215540,-33.880290,True,95.0,0,13764143,Ben,Surry Hills,"New South Wales, Australia",government_id
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,,,,,...,29.030790,40.985630,False,0.0,365,51303748,Eren,,"Kadikoy, Çanakkale, Turkey",0
5551,9993190,https://www.airbnb.com/rooms/9993190,Just Steps from the Ocean at Premier Platinum ...,Relax Hawaiian Style in Gated Community on Oce...,"***NOTE: THE OCEAN INFINITY POOL (""POOL 1""0 WI...",Relax Hawaiian Style in Gated Community on Oce...,Location: Located at the south end of Lahaina ...,Puamana Resort requires a $10/day resort fee w...,You can walk to most attractions within Lahain...,Guests will have access to the 3 pools in the ...,...,-156.667520,20.858940,False,92.0,258,51013381,Coconut Condos,,"Lahaina, Hawaii, United States",0
5552,9887054,https://www.airbnb.com/rooms/9887054,Quarry Bay fully furnished studio C,Newly renovated studio flat with full furniture.,,Newly renovated studio flat with full furniture.,,,,,...,114.207220,22.291570,False,85.0,353,31386255,Cat,Causeway Bay,Hong Kong,0
5553,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,A bright large double room is available in a b...,,A bright large double room is available in a b...,,,The flat is exactly half way between the shops...,"Guests will have access to the full residence,...",...,151.265420,-33.892980,False,0.0,0,47615848,Lucy,,"Bondi Beach, New South Wales, Australia",0
5554,9936016,https://www.airbnb.com/rooms/9936016,Alugo Apartamento na Tijuca,Apartamento amplo que acomoda 6 pessoas. Um qu...,,Apartamento amplo que acomoda 6 pessoas. Um qu...,,,,,...,-43.173761,-22.908336,False,0.0,0,47092481,Aliane,,BR,0

In [54]:
df.isnull().mean()

_id                      0.000000
listing_url              0.000000
name                     0.000000
summary                  0.000000
space                    0.000000
description              0.000000
neighborhood_overview    0.000000
notes                    0.000000
transit                  0.000000
access                   0.000000
interaction              0.000000
house_rules              0.000000
property_type            0.000000
room_type                0.000000
bed_type                 0.000000
minimum_nights           0.000000
maximum_nights           0.000000
cancellation_policy      0.000000
last_scraped             0.000000
calendar_last_scraped    0.000000
first_review             0.249865
last_review              0.249865
accommodates             0.000000
bedrooms                 0.000900
beds                     0.002340
number_of_reviews        0.000000
bathrooms                0.001800
amenities                0.000000
price                    0.000000
security_deposit         0.375158
cleaning_fee             0.275608
extra_people             0.000000
guests_included          0.000000
images                   0.000000
host                     0.000000
address                  0.000000
availability             0.000000
review_scores            0.000000
reviews                  0.000000
weekly_price             0.871467
monthly_price            0.881908
reviews_per_month        0.983078
street_name              0.000000
country_name             0.000000
country_code             0.000000
location_type            0.000000
longitude                0.000000
latitude                 0.000000
is_location_exact        0.000000
review_scores_rating     0.265347
availability_365         0.000000
host_id                  0.000000
host_name                0.000000
host_neighbourhood       0.000000
host_location            0.000000
government_id            0.433663
dtype: float64

In [55]:
#df.to_csv('output.csv', index=False)

In [56]:
df[['latitude','longitude','country_name']]

       latitude   longitude   country_name
0     40.799620  -73.965230  United States
1     41.006200   28.980090         Turkey
2     22.281580  114.150270      Hong Kong
3     22.331400  114.166900      Hong Kong
4    -33.880290  151.215540      Australia
...         ...         ...            ...
5550  40.985630   29.030790         Turkey
5551  20.858940 -156.667520  United States
5552  22.291570  114.207220      Hong Kong
5553 -33.892980  151.265420      Australia
5554 -22.908336  -43.173761         Brazil

[5555 rows x 3 columns]

In [57]:
df['country_name'].value_counts()

country_name
United States    1222
Turkey            661
Canada            649
Spain             633
Australia         610
Brazil            606
Hong Kong         600
Portugal          555
China              19
Name: count, dtype: int64

In [58]:
df['property_type'].value_counts()

property_type
Apartment                 3626
House                      606
Condominium                399
Serviced apartment         185
Loft                       142
Townhouse                  108
Guest suite                 81
Bed and breakfast           69
Boutique hotel              53
Guesthouse                  50
Hostel                      34
Villa                       32
Hotel                       26
Aparthotel                  23
Cottage                     20
Other                       18
Cabin                       15
Bungalow                    14
Resort                      11
Farm stay                    9
Casa particular (Cuba)       9
Tiny house                   7
Boat                         2
Nature lodge                 2
Chalet                       2
Camper/RV                    2
Pension (South Korea)        1
Houseboat                    1
Castle                       1
Campsite                     1
Treehouse                    1
Heritage hotel (India)       1
Hut                          1
Barn                         1
Earth house                  1
Train                        1
Name: count, dtype: int64

In [59]:
df['room_type'].value_counts()

room_type
Entire home/apt    3489
Private room       1983
Shared room          83
Name: count, dtype: int64

In [60]:
df[['property_type','accommodates']].value_counts().head(10)

property_type  accommodates
Apartment      2               1395
               4                760
               1                407
               3                377
               6                297
House          2                192
Apartment      5                179
Condominium    4                121
               2                104
Apartment      8                 88
Name: count, dtype: int64

In [72]:
df['review_scores_rating'].mean()

93.09924038225925

In [74]:
df.groupby('country_name')['review_scores_rating'].mean()

country_name
Australia        93.469136
Brazil           94.813953
Canada           92.888664
China            90.166667
Hong Kong        91.422018
Portugal         93.696970
Spain            90.911392
Turkey           91.594156
United States    94.343662
Name: review_scores_rating, dtype: float64

In [75]:
df.groupby('room_type')['review_scores_rating'].mean()

room_type
Entire home/apt    93.502396
Private room       92.359788
Shared room        90.533333
Name: review_scores_rating, dtype: float64

In [76]:
df.groupby('property_type')['review_scores_rating'].mean()

property_type
Aparthotel                 88.285714
Apartment                  92.929131
Barn                       98.000000
Bed and breakfast          91.971429
Boat                       82.000000
Boutique hotel             91.687500
Bungalow                   97.083333
Cabin                      94.285714
Camper/RV                 100.000000
Campsite                   94.000000
Casa particular (Cuba)     75.000000
Castle                           NaN
Chalet                     92.000000
Condominium                93.778878
Cottage                    94.529412
Earth house               100.000000
Farm stay                  96.714286
Guest suite                95.956522
Guesthouse                 94.530612
Heritage hotel (India)           NaN
Hostel                     86.315789
Hotel                      86.437500
House                      93.736239
Houseboat                  90.000000
Hut                        95.000000
Loft                       94.061947
Nature lodge               89.000000
Other                      90.888889
Pension (South Korea)      89.000000
Resort                     92.500000
Serviced apartment         91.366667
Tiny house                 90.400000
Townhouse                  95.388889
Train                      99.000000
Treehouse                  99.000000
Villa                      89.555556
Name: review_scores_rating, dtype: float64

host_name
(Email hidden by Airbnb)      NaN
(Joe)  American Club         70.0
08028 Apartments              NaN
194 Porto.Flats             100.0
24 Eight Guesthouse          94.0
                            ...
陈                             NaN
霖华                           96.0
飞飞                           90.0
香蕉宿黑金厂民宿精品酒店                  NaN
馨                            95.0
Name: review_scores_rating, Length: 3140, dtype: float64